### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of org.slf4j:slf4j-api:jar

### ISSUE THREAD

**Issue by Bing-ok** [Dromara/myth#68]
Hi, there are multiple versions of <b><i>org.slf4j:slf4j-api</i></b> in <b><i>myth-master\myth-rpc\myth-motan</i></b>. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only <b><i>org.slf4j:slf4j-api:1.7.25</i></b> can be loaded, and <b><i>org.slf4j:slf4j-api:1.5.8</i></b> will be shadowed.

As <b><i>org.slf4j:slf4j-api:1.5.8</i></b> has not been loaded during the building process, several methods are missing. However, the missing methods:
<b><i>1. org.slf4j.helpers.MessageFormatter: java.lang.String format(java.lang.String,java.lang.Object)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;org.dromara.myth.motan.interceptor.MotanMythTransactionInterceptor: java.lang.Object interceptor(org.aspectj.lang.ProceedingJoinPoint)&gt; myth-master\myth-rpc\myth-motan\target\classes
</br>&lt;org.dromara.myth.core.service.impl.MythTransactionAspectServiceImpl: java.lang.Object invoke(org.dromara.myth.common.bean.context.MythTransactionContext,org.aspectj.lang.ProceedingJoinPoint)&gt; Repositories\org\dromara\myth-core\2.0.2-RELEASE\myth-core-2.0.2-RELEASE.jar
</br>&lt;org.dromara.myth.core.service.handler.ActorMythTransactionHandler: java.lang.Object handler(org.aspectj.lang.ProceedingJoinPoint,org.dromara.myth.common.bean.context.MythTransactionContext)&gt; Repositories\org\dromara\myth-core\2.0.2-RELEASE\myth-core-2.0.2-RELEASE.jar
</br>&lt;org.dromara.myth.common.utils.LogUtil: void error(org.slf4j.Logger,java.lang.String,java.util.function.Supplier)&gt; Repositories\org\dromara\myth-common\2.0.2-RELEASE\myth-common-2.0.2-RELEASE.jar
</br>&lt;org.slf4j.impl.Log4jLoggerAdapter: void error(java.lang.String,java.lang.Object)&gt; Repositories\org\slf4j\slf4j-log4j12\1.7.25\slf4j-log4j12-1.7.25.jar
</br>&lt;org.slf4j.helpers.MessageFormatter: java.lang.String format(java.lang.String,java.lang.Object)&gt; 
</details>

The above missing methods are actually referenced by <b><i>myth-master\myth-rpc\myth-motan</i></b>, which will cause “NoSuchMethodErrors” at runtime.

Suggested fixing solutions:
1. Upgrading dependency <b><i>com.weibo:motan-core</i></b>, <b><i>com.weibo:motan-springsupport</i></b> and <b><i>com.weibo:motan-transport-netty</i></b> from <b><i>1.0.0</i></b> to <b><i>1.1.2</i></b> can solve this dependency conflict.
2. Change dependency <b><i>org.slf4j:slf4j-api</i></b> from <b><i>1.7.25</i></b> to <b><i>1.5.8</i></b>.
3. Use configuration attribute &lt;dependencyManagement&gt; to unify the version of library <b><i>org.slf4j:slf4j-api</i></b> to be <b><i>1.5.8</i></b> in myth-master\myth-rpc\myth-motan's pom file.

Please let me know which solution do you prefer? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

Dependency tree----
<details>
<summary>click for details</summary>
</br>[INFO] org.dromara:myth-motan:jar:2.0.2-RELEASE
</br>[INFO] +- org.dromara:myth-core:jar:2.0.2-RELEASE:compile
</br>[INFO] |  +- org.dromara:myth-common:jar:2.0.2-RELEASE:compile
</br>[INFO] |  |  +- (org.dromara:myth-annotation:jar:2.0.2-RELEASE:compile - omitted for duplicate)
</br>[INFO] |  |  +- (org.apache.commons:commons-lang3:jar:3.3.2:compile - omitted for duplicate)
</br>[INFO] |  |  +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
</br>[INFO] |  |  |  \- commons-collections:commons-collections:jar:3.2.2:compile
</br>[INFO] |  |  +- <b>org.slf4j:slf4j-api:jar:1.7.25:compile</b>
</br>[INFO] |  |  +- ch.qos.logback:logback-core:jar:1.2.3:compile
</br>[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
</br>[INFO] |  |  |  +- (ch.qos.logback:logback-core:jar:1.2.3:compile - omitted for duplicate)
</br>[INFO] |  |  |  \- (org.slf4j:slf4j-api:jar:1.7.25:compile - omitted for duplicate)
</br>[INFO] |  |  +- com.google.code.gson:gson:jar:2.6.2:compile
</br>[INFO] |  |  +- com.squareup.okhttp3:okhttp:jar:3.7.0:compile
</br>[INFO] |  |  |  \- com.squareup.okio:okio:jar:1.12.0:compile
</br>[INFO] |  |  +- com.google.guava:guava:jar:21.0:compile
</br>[INFO] |  |  +- redis.clients:jedis:jar:2.9.0:compile
</br>[INFO] |  |  |  \- org.apache.commons:commons-pool2:jar:2.6.0:compile (version managed from 2.4.2)
</br>[INFO] |  |  +- org.projectlombok:lombok:jar:1.16.20:compile
</br>[INFO] |  |  +- com.esotericsoftware:kryo-shaded:jar:4.0.0:compile
</br>[INFO] |  |  |  +- com.esotericsoftware:minlog:jar:1.3.0:compile
</br>[INFO] |  |  |  \- org.objenesis:objenesis:jar:2.2:compile
</br>[INFO] |  |  +- com.dyuproject.protostuff:protostuff-core:jar:1.0.8:compile
</br>[INFO] |  |  |  \- com.dyuproject.protostuff:protostuff-api:jar:1.0.8:compile
</br>[INFO] |  |  +- com.dyuproject.protostuff:protostuff-runtime:jar:1.0.8:compile
</br>[INFO] |  |  |  +- (com.dyuproject.protostuff:protostuff-api:jar:1.0.8:compile - omitted for duplicate)
</br>[INFO] |  |  |  \- com.dyuproject.protostuff:protostuff-collectionschema:jar:1.0.8:compile
</br>[INFO] |  |  |     \- (com.dyuproject.protostuff:protostuff-api:jar:1.0.8:compile - omitted for duplicate)
</br>[INFO] |  |  +- com.caucho:hessian:jar:4.0.38:compile
</br>[INFO] |  |  \- org.mongodb:mongo-java-driver:jar:3.5.0:compile
</br>[INFO] |  +- org.dromara:myth-annotation:jar:2.0.2-RELEASE:compile
</br>[INFO] |  +- org.aspectj:aspectjweaver:jar:1.8.9:compile
</br>[INFO] |  +- com.lmax:disruptor:jar:3.4.0:compile
</br>[INFO] |  \- org.apache.zookeeper:zookeeper:jar:3.4.9:compile
</br>[INFO] |     +- (org.slf4j:slf4j-api:jar:1.7.25:compile - version managed from 1.6.1; omitted for duplicate)
</br>[INFO] |     +- log4j:log4j:jar:1.2.14:compile
</br>[INFO] |     +- jline:jline:jar:0.9.94:compile
</br>[INFO] |     \- io.netty:netty:jar:3.10.5.Final:compile
</br>[INFO] +- org.apache.commons:commons-lang3:jar:3.3.2:compile
</br>[INFO] +- org.springframework:spring-context:jar:5.1.3.RELEASE:provided
</br>[INFO] |  +- org.springframework:spring-aop:jar:5.1.3.RELEASE:provided
</br>[INFO] |  |  +- (org.springframework:spring-beans:jar:5.1.3.RELEASE:provided - omitted for duplicate)
</br>[INFO] |  |  \- (org.springframework:spring-core:jar:5.1.3.RELEASE:provided - omitted for duplicate)
</br>[INFO] |  +- org.springframework:spring-beans:jar:5.1.3.RELEASE:provided
</br>[INFO] |  |  \- (org.springframework:spring-core:jar:5.1.3.RELEASE:provided - omitted for duplicate)
</br>[INFO] |  +- org.springframework:spring-core:jar:5.1.3.RELEASE:provided
</br>[INFO] |  |  \- org.springframework:spring-jcl:jar:5.1.3.RELEASE:provided
</br>[INFO] |  \- org.springframework:spring-expression:jar:5.1.3.RELEASE:provided
</br>[INFO] |     \- (org.springframework:spring-core:jar:5.1.3.RELEASE:provided - omitted for duplicate)
</br>[INFO] +- com.weibo:motan-core:jar:1.0.0:provided
</br>[INFO] |  +- commons-pool:commons-pool:jar:1.6:provided
</br>[INFO] |  +- (com.caucho:hessian:jar:4.0.38:compile - scope updated from provided; omitted for duplicate)
</br>[INFO] |  +- com.alibaba:fastjson:jar:1.1.30:provided
</br>[INFO] |  +- com.codahale.metrics:metrics-core:jar:3.0.1:provided
</br>[INFO] |  |  \- <b>(org.slf4j:slf4j-api:jar:1.7.25:provided - version managed from 1.7.5; omitted for duplicate)</b>
</br>[INFO] |  +- (com.google.guava:guava:jar:21.0:compile - version managed from 18.0; scope updated from provided; omitted for duplicate)
</br>[INFO] |  +- com.squareup:javapoet:jar:1.8.0:provided
</br>[INFO] |  +- (org.slf4j:slf4j-api:jar:1.7.25:compile - version managed from 1.5.8; scope updated from provided; omitted for duplicate)
</br>[INFO] |  +- <b>org.slf4j:slf4j-log4j12:jar:1.7.25:provided (version managed from 1.5.8)</b>
</br>[INFO] |  |  +- <b>(org.slf4j:slf4j-api:jar:1.7.25:provided - version managed from 1.5.8; omitted for duplicate)</b>
</br>[INFO] |  |  \- (log4j:log4j:jar:1.2.17:provided - omitted for conflict with 1.2.14)
</br>[INFO] |  +- (log4j:log4j:jar:1.2.14:compile - scope updated from provided; omitted for duplicate)
</br>[INFO] |  +- (org.apache.commons:commons-lang3:jar:3.3.2:provided - version managed from 3.1; omitted for duplicate)
</br>[INFO] |  \- commons-codec:commons-codec:jar:1.11:provided (version managed from 1.4)
</br>[INFO] +- com.weibo:motan-springsupport:jar:1.0.0:provided
</br>[INFO] |  +- (com.weibo:motan-core:jar:1.0.0:provided - omitted for duplicate)
</br>[INFO] |  +- <b>(org.slf4j:slf4j-api:jar:1.7.25:compile - version managed from 1.5.8; scope updated from provided; omitted for duplicate)</b>
</br>[INFO] |  +- (org.slf4j:slf4j-log4j12:jar:1.7.25:provided - version managed from 1.5.8; omitted for duplicate)
</br>[INFO] |  +- (log4j:log4j:jar:1.2.14:compile - scope updated from provided; omitted for duplicate)
</br>[INFO] |  +- (org.apache.commons:commons-lang3:jar:3.3.2:provided - version managed from 3.1; omitted for duplicate)
</br>[INFO] |  \- (commons-codec:commons-codec:jar:1.11:provided - version managed from 1.4; omitted for duplicate)
</br>[INFO] \- com.weibo:motan-transport-netty:jar:1.0.0:provided
</br>[INFO]    +- org.jboss.netty:netty:jar:3.2.5.Final:provided
</br>[INFO]    +- (com.weibo:motan-core:jar:1.0.0:provided - omitted for duplicate)
</br>[INFO]    +- <b>(org.slf4j:slf4j-api:jar:1.7.25:compile - version managed from 1.5.8; scope updated from provided; omitted for duplicate)</b>
</br>[INFO]    +- (org.slf4j:slf4j-log4j12:jar:1.7.25:provided - version managed from 1.5.8; omitted for duplicate)
</br>[INFO]    +- (log4j:log4j:jar:1.2.14:compile - scope updated from provided; omitted for duplicate)
</br>[INFO]    +- (org.apache.commons:commons-lang3:jar:3.3.2:provided - version managed from 3.1; omitted for duplicate)
</br>[INFO]    \- (commons-codec:commons-codec:jar:1.11:provided - version managed from 1.4; omitted for duplicate)
</details>

**Comment by Bing-ok** [comment]
![捕获](https://user-images.githubusercontent.com/66594914/90329633-2501e580-dfd9-11ea-8a77-2cf26b27bb64.JPG)
About solution No.1

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @yu199195

**Comment by yu199195** [comment]
@Bing-ok  hi， solution 3 maybe good idea， you can pr  fix it

**Comment by Bing-ok** [comment]
Thanks for your support!
